Import('env2', 'objs')
env2.Program('host', source=['host.cpp', objs], 
            CCFLAGS=' -O2  -std=c++0x', 
           CPPPATH = ['/opt/intel/opencl-sdk/include/','#util'],
           LIBS=['OpenCL'],LIBPATH='/opt/intel/opencl-sdk/lib64')
